export const googData = {
    "range": "qcsample!A1:X38",
    "majorDimension": "ROWS",
    "values": [
        [
            "Item",
            "Label",
            "Structure -->",
            "Groups",
            "Subgroup",
            "Description Options -->",
            "Description",
            "AllowedMin",
            "AllowedMax",
            "Unit",
            "SD",
            "Mean",
            "CV",
            "Status",
            "Analysis dates -->",
            "Presenting",
            "Date1",
            "Date2",
            "Date3",
            "Date4",
            "Date5",
            "Date6",
            "Date7",
            "Date8"
        ],
        [
            "QC-008",
            "",
            "",
            "QCSample",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "Err-range",
            "11/2023 9:00:00; 2/1/2023 9:00:01; 3/1/2023 9:00:02; 4/1/2023 9:00:03; 5/1/2023 9:00:04; 6/1/2023 9:00:05; 7/1/2023 9:00:06; 8/1/2023 9:00:07",
            "10/4/2023 0:00:00",
            "11/2023 9:00:00",
            "2/1/2023 9:00:01",
            "3/1/2023 9:00:02",
            "4/1/2023 9:00:03",
            "5/1/2023 9:00:04",
            "6/1/2023 9:00:05",
            "7/1/2023 9:00:06",
            "8/1/2023 9:00:07"
        ],
        [
            "Material",
            "",
            "",
            "QC-008",
            "SampleInfo",
            "",
            "XN-L Control Level 1"
        ],
        [
            "Expiry Date",
            "",
            "",
            "QC-008",
            "SampleInfo",
            "",
            "31/08/2023"
        ],
        [
            "Cell Pack DCL",
            "",
            "",
            "QC-008",
            "ReagentInfo"
        ],
        [
            "Validated",
            "",
            "",
            "QC-008",
            "RunInfo"
        ],
        [
            "Output",
            "",
            "",
            "QC-008",
            "RunInfo"
        ],
        [
            "P / N",
            "",
            "",
            "QC-008",
            "RunInfo"
        ],
        [
            "Rack no.",
            "Rack #",
            "",
            "QC-008",
            "RunInfo"
        ],
        [
            "Position",
            "",
            "",
            "QC-008",
            "RunInfo"
        ],
        [
            "Action",
            "",
            "",
            "QC-008",
            "RunInfo"
        ],
        [
            "Error",
            "",
            "",
            "QC-008",
            "RunInfo"
        ],
        [
            "WBC",
            "WBC<sup>+4</sup>",
            "",
            "QC-008",
            "HAParameter",
            "",
            "",
            "2.02",
            "2.73",
            "x 10^3/μL",
            "0.20",
            "2.38",
            "0.09",
            "",
            "",
            "2.31",
            "2.50",
            "2.59",
            "2.55",
            "2.09",
            "2.43",
            "2.08",
            "2.22",
            "2.23"
        ],
        [
            "RBC",
            "RBC<sup>+4</sup>",
            "",
            "QC-008",
            "HAParameter",
            "",
            "",
            "2.17",
            "2.39",
            "x 10^6/μL",
            "0.10",
            "2.28",
            "0.04",
            "",
            "",
            "2.27",
            "2.00",
            "2.26",
            "2.25",
            "2.20",
            "2.22",
            "2.19",
            "2.34",
            "2.24"
        ],
        [
            "Hematocrit",
            "",
            "",
            "QC-008",
            "HAParameter",
            "",
            "",
            "15.4",
            "17.7",
            "%",
            "0.56",
            "16.55",
            "0.03",
            "",
            "",
            "17.35",
            "17.57",
            "16.52",
            "16.01",
            "16.20",
            "16.78",
            "16.86",
            "16.55",
            "15.78"
        ],
        [
            "Hemoglobin",
            "HGB<sup>+4</sup>",
            "",
            "#REF!",
            "HAParameter",
            "",
            "",
            "5.4",
            "5.9",
            "g/dL",
            "0.14",
            "5.65",
            "0.02",
            "",
            "",
            "5.62",
            "5.50",
            "5.68",
            "5.73",
            "5.81",
            "5.83",
            "5.74",
            "5.80",
            "5.46"
        ],
        [
            "MCV",
            "",
            "",
            "QC-008",
            "HAParameter",
            "",
            "",
            "75.6",
            "106.3",
            "fL",
            "7.55",
            "90.95",
            "0.08",
            "",
            "",
            "105.70",
            "96.87",
            "92.68",
            "81.90",
            "78.06",
            "92.51",
            "94.26",
            "96.62",
            "99.31"
        ],
        [
            "MCH",
            "",
            "",
            "QC-008",
            "HAParameter",
            "",
            "",
            "26.0",
            "36.4",
            "pg",
            "2.16",
            "31.20",
            "0.07",
            "",
            "",
            "30.75",
            "28.62",
            "30.63",
            "35.58",
            "31.59",
            "32.49",
            "33.56",
            "31.14",
            "30.13"
        ],
        [
            "MCHC",
            "",
            "",
            "QC-008",
            "HAParameter",
            "",
            "",
            "33.6",
            "35.7",
            "g/dL",
            "0.73",
            "34.65",
            "0.02",
            "",
            "",
            "34.62",
            "33.72",
            "33.63",
            "33.85",
            "33.68",
            "35.37",
            "35.08",
            "34.65",
            "35.04"
        ],
        [
            "Platelet",
            "",
            "",
            "QC-008",
            "HAParameter",
            "",
            "",
            "95.0",
            "471.0",
            "x 10^3/μL",
            "68.05",
            "283.00",
            "0.24",
            "",
            "",
            "341.92",
            "290.08",
            "197.86",
            "181.16",
            "301.72",
            "274.01",
            "176.24",
            "154.10",
            "119.01"
        ],
        [
            "RDW-SD",
            "",
            "",
            "QC-008",
            "HAParameter",
            "",
            "",
            "34.9",
            "65.7",
            "fL",
            "6.54",
            "50.30",
            "0.13",
            "",
            "",
            "36.10",
            "48.84",
            "59.53",
            "43.97",
            "51.74",
            "41.82",
            "56.02",
            "41.83",
            "50.98"
        ],
        [
            "RDW-CV",
            "",
            "",
            "QC-008",
            "HAParameter",
            "",
            "",
            "13.3",
            "18.2",
            "%",
            "1.32",
            "15.75",
            "0.08",
            "",
            "",
            "15.79",
            "13.57",
            "14.71",
            "15.13",
            "15.62",
            "16.09",
            "17.00",
            "14.21",
            "17.36"
        ],
        [
            "MPV",
            "",
            "",
            "QC-008",
            "HAParameter",
            "",
            "",
            "7.3",
            "9.9",
            "fL",
            "0.72",
            "8.60",
            "0.08",
            "",
            "",
            "9.46",
            "8.71",
            "9.74",
            "7.91",
            "9.03",
            "9.70",
            "9.60",
            "8.21",
            "8.37"
        ],
        [
            "Neutrophils no.",
            "Neutrophils #",
            "",
            "QC-008",
            "HAParameter",
            "",
            "",
            "2.2",
            "11.4",
            "x 10^3/μL",
            "3.33",
            "6.80",
            "0.49",
            "",
            "",
            "9.60",
            "2.27",
            "8.21",
            "2.26",
            "3.55",
            "2.36",
            "11.14",
            "2.78",
            "5.86"
        ],
        [
            "Lymphocytes no.",
            "Lymphocytes #",
            "",
            "QC-008",
            "HAParameter",
            "",
            "",
            "1.2",
            "5.7",
            "x 10^3/μL",
            "1.57",
            "3.45",
            "0.45",
            "",
            "",
            "3.59",
            "1.48",
            "3.14",
            "5.43",
            "4.92",
            "1.41",
            "2.32",
            "3.14",
            "4.74"
        ],
        [
            "Monocytes no.",
            "Monocytes #",
            "",
            "QC-008",
            "HAParameter",
            "",
            "",
            "0.1",
            "5.0",
            "x 10^3/μL",
            "1.23",
            "2.55",
            "0.48",
            "",
            "",
            "0.29",
            "1.18",
            "1.22",
            "0.63",
            "2.83",
            "2.13",
            "1.61",
            "3.17",
            "4.30"
        ],
        [
            "Eosinophils no.",
            "Eosinophils #",
            "",
            "QC-008",
            "HAParameter",
            "",
            "",
            "0.0",
            "0.5",
            "x 10^3/μL",
            "0.18",
            "0.25",
            "0.70",
            "",
            "",
            "0.08",
            "0.04",
            "0.49",
            "0.31",
            "0.15",
            "0.04",
            "0.02",
            "0.33",
            "0.06"
        ],
        [
            "Basophils no.",
            "Basophils #",
            "",
            "QC-008",
            "HAParameter",
            "",
            "",
            "0.0",
            "0.1",
            "x 10^3/μL",
            "0.04",
            "0.05",
            "0.71",
            "",
            "",
            "0.09",
            "0.09",
            "0.06",
            "0.01",
            "0.00",
            "0.03",
            "0.06",
            "0.02",
            "0.10"
        ],
        [
            "Neutrophils percent",
            "Neutrophils %",
            "",
            "QC-008",
            "HAParameter",
            "",
            "",
            "14.6",
            "69.3",
            "%",
            "10.65",
            "41.95",
            "0.25",
            "",
            "",
            "67.14",
            "49.53",
            "59.76",
            "43.49",
            "54.12",
            "25.95",
            "48.41",
            "35.86",
            "49.10"
        ],
        [
            "Lymphocytes percent",
            "Lymphocytes %",
            "",
            "QC-008",
            "HAParameter",
            "",
            "",
            "8.0",
            "70.0",
            "%",
            "21.92",
            "39.00",
            "0.56",
            "",
            "",
            "68.06",
            "62.95",
            "23.43",
            "69.22",
            "19.11",
            "24.22",
            "11.97",
            "31.93",
            "14.14"
        ],
        [
            "Monocytes percent",
            "Monocytes %",
            "",
            "QC-008",
            "HAParameter",
            "",
            "",
            "4.0",
            "19.0",
            "%",
            "2.66",
            "11.50",
            "0.23",
            "",
            "",
            "11.84",
            "13.76",
            "8.17",
            "10.09",
            "14.21",
            "15.48",
            "12.84",
            "9.04",
            "10.52"
        ],
        [
            "Eosinophils percent",
            "Eosinophils %",
            "",
            "QC-008",
            "HAParameter",
            "",
            "",
            "1.0",
            "7.0",
            "%",
            "2.06",
            "4.00",
            "0.51",
            "",
            "",
            "4.37",
            "3.43",
            "4.11",
            "2.65",
            "1.18",
            "2.26",
            "6.00",
            "6.80",
            "6.15"
        ],
        [
            "Basophils percent",
            "Basophils %",
            "",
            "QC-008",
            "HAParameter",
            "",
            "",
            "0.0",
            "1.0",
            "%",
            "0.37",
            "0.50",
            "0.75",
            "",
            "",
            "0.42",
            "0.10",
            "0.84",
            "0.61",
            "0.84",
            "0.99",
            "0.87",
            "0.89",
            "0.03"
        ],
        [
            "IG no.",
            "",
            "",
            "QC-008",
            "HAParameter",
            "",
            "",
            "0.0",
            "0.28",
            "x 10^3/μL%",
            "0.07",
            "0.14",
            "0.48",
            "",
            "",
            "0.16",
            "0.14",
            "0.04",
            "0.13",
            "0.17",
            "0.10",
            "0.10",
            "0.23",
            "0.23"
        ],
        [
            "IG percent",
            "",
            "",
            "QC-008",
            "HAParameter",
            "",
            "",
            "0.0",
            "1.7",
            "%",
            "0.44",
            "0.85",
            "0.52",
            "",
            "",
            "0.61",
            "0.25",
            "1.45",
            "0.85",
            "0.24",
            "0.33",
            "0.86",
            "0.48",
            "0.17"
        ],
        [
            "RET no.",
            "",
            "",
            "QC-008",
            "HAParameter",
            "",
            "",
            "29.0",
            "120.0",
            "x 10^6/μL",
            "15.13",
            "74.50",
            "0.20",
            "",
            "",
            "73.32",
            "74.85",
            "64.07",
            "65.74",
            "61.19",
            "87.36",
            "100.05",
            "92.74",
            "63.84"
        ],
        [
            "RET percent",
            "",
            "",
            "QC-008",
            "HAParameter",
            "",
            "",
            "0.4",
            "4.8",
            "%",
            "1.38",
            "2.60",
            "0.53",
            "",
            "",
            "4.80",
            "3.37",
            "3.84",
            "3.00",
            "4.13",
            "0.81",
            "0.54",
            "2.44",
            "1.41"
        ]
    ]
};

export const parsedRowData = [
    {
        "Item": "QC-001",
        "Label": "",
        "Structure -->": "",
        "Groups": "QCSample",
        "Subgroup": "",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "",
        "AllowedMax": "",
        "Unit": "",
        "SD": "",
        "Mean": "",
        "CV": "",
        "Status": "Err-range",
        "Analysis dates -->": "11/2023 9:00:00; 2/1/2023 9:00:01; 3/1/2023 9:00:02; 4/1/2023 9:00:03; 5/1/2023 9:00:04; 6/1/2023 9:00:05; 7/1/2023 9:00:06; 8/1/2023 9:00:07",
        "Presenting": "10/3/2023 0:00:00",
        "Date1": "11/2023 9:00:00",
        "Date2": "2/1/2023 9:00:01",
        "Date3": "3/1/2023 9:00:02",
        "Date4": "4/1/2023 9:00:03",
        "Date5": "5/1/2023 9:00:04",
        "Date6": "6/1/2023 9:00:05",
        "Date7": "7/1/2023 9:00:06",
        "Date8": "8/1/2023 9:00:07"
    },
    {
        "Item": "Material",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-001",
        "Subgroup": "SampleInfo",
        "Description Options -->": "",
        "Description": "XN-L Control Level 1"
    },
    {
        "Item": "Expiry Date",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-001",
        "Subgroup": "SampleInfo",
        "Description Options -->": "",
        "Description": "31/08/2023"
    },
    {
        "Item": "Cell Pack DCL",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-001",
        "Subgroup": "ReagentInfo"
    },
    {
        "Item": "Validated",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-001",
        "Subgroup": "RunInfo"
    },
    {
        "Item": "Output",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-001",
        "Subgroup": "RunInfo"
    },
    {
        "Item": "P / N",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-001",
        "Subgroup": "RunInfo"
    },
    {
        "Item": "Rack no.",
        "Label": "Rack #",
        "Structure -->": "",
        "Groups": "QC-001",
        "Subgroup": "RunInfo"
    },
    {
        "Item": "Position",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-001",
        "Subgroup": "RunInfo"
    },
    {
        "Item": "Action",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-001",
        "Subgroup": "RunInfo"
    },
    {
        "Item": "Error",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-001",
        "Subgroup": "RunInfo"
    },
    {
        "Item": "WBC",
        "Label": "WBC<sup>+4</sup>",
        "Structure -->": "",
        "Groups": "QC-001",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "2.02",
        "AllowedMax": "2.73",
        "Unit": "x 10^3/μL",
        "SD": "0.20",
        "Mean": "2.38",
        "CV": "0.09",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "2.31",
        "Date1": "2.50",
        "Date2": "2.59",
        "Date3": "2.55",
        "Date4": "2.09",
        "Date5": "2.43",
        "Date6": "2.08",
        "Date7": "2.22",
        "Date8": "2.23"
    },
    {
        "Item": "RBC",
        "Label": "RBC<sup>+4</sup>",
        "Structure -->": "",
        "Groups": "QC-001",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "2.17",
        "AllowedMax": "2.39",
        "Unit": "x 10^6/μL",
        "SD": "0.10",
        "Mean": "2.28",
        "CV": "0.04",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "2.27",
        "Date1": "2.00",
        "Date2": "2.26",
        "Date3": "2.25",
        "Date4": "2.20",
        "Date5": "2.22",
        "Date6": "2.19",
        "Date7": "2.34",
        "Date8": "2.24"
    },
    {
        "Item": "Hematocrit",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-001",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "15.4",
        "AllowedMax": "17.7",
        "Unit": "%",
        "SD": "0.56",
        "Mean": "16.55",
        "CV": "0.03",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "17.35",
        "Date1": "17.57",
        "Date2": "16.52",
        "Date3": "16.01",
        "Date4": "16.20",
        "Date5": "16.78",
        "Date6": "16.86",
        "Date7": "16.55",
        "Date8": "15.78"
    },
    {
        "Item": "Hemoglobin",
        "Label": "HGB<sup>+4</sup>",
        "Structure -->": "",
        "Groups": "QC-003",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "5.4",
        "AllowedMax": "5.9",
        "Unit": "g/dL",
        "SD": "0.14",
        "Mean": "5.65",
        "CV": "0.02",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "5.62",
        "Date1": "5.50",
        "Date2": "5.68",
        "Date3": "5.73",
        "Date4": "5.81",
        "Date5": "5.83",
        "Date6": "5.74",
        "Date7": "5.80",
        "Date8": "5.46"
    },
    {
        "Item": "MCV",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-001",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "75.6",
        "AllowedMax": "106.3",
        "Unit": "fL",
        "SD": "7.55",
        "Mean": "90.95",
        "CV": "0.08",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "105.70",
        "Date1": "96.87",
        "Date2": "92.68",
        "Date3": "81.90",
        "Date4": "78.06",
        "Date5": "92.51",
        "Date6": "94.26",
        "Date7": "96.62",
        "Date8": "99.31"
    },
    {
        "Item": "MCH",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-001",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "26.0",
        "AllowedMax": "36.4",
        "Unit": "pg",
        "SD": "2.16",
        "Mean": "31.20",
        "CV": "0.07",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "30.75",
        "Date1": "28.62",
        "Date2": "30.63",
        "Date3": "35.58",
        "Date4": "31.59",
        "Date5": "32.49",
        "Date6": "33.56",
        "Date7": "31.14",
        "Date8": "30.13"
    },
    {
        "Item": "MCHC",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-001",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "33.6",
        "AllowedMax": "35.7",
        "Unit": "g/dL",
        "SD": "0.73",
        "Mean": "34.65",
        "CV": "0.02",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "34.62",
        "Date1": "33.72",
        "Date2": "33.63",
        "Date3": "33.85",
        "Date4": "33.68",
        "Date5": "35.37",
        "Date6": "35.08",
        "Date7": "34.65",
        "Date8": "35.04"
    },
    {
        "Item": "Platelet",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-001",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "95.0",
        "AllowedMax": "471.0",
        "Unit": "x 10^3/μL",
        "SD": "68.05",
        "Mean": "283.00",
        "CV": "0.24",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "341.92",
        "Date1": "290.08",
        "Date2": "197.86",
        "Date3": "181.16",
        "Date4": "301.72",
        "Date5": "274.01",
        "Date6": "176.24",
        "Date7": "154.10",
        "Date8": "119.01"
    },
    {
        "Item": "RDW-SD",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-001",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "34.9",
        "AllowedMax": "65.7",
        "Unit": "fL",
        "SD": "6.54",
        "Mean": "50.30",
        "CV": "0.13",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "36.10",
        "Date1": "48.84",
        "Date2": "59.53",
        "Date3": "43.97",
        "Date4": "51.74",
        "Date5": "41.82",
        "Date6": "56.02",
        "Date7": "41.83",
        "Date8": "50.98"
    },
    {
        "Item": "RDW-CV",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-001",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "13.3",
        "AllowedMax": "18.2",
        "Unit": "%",
        "SD": "1.32",
        "Mean": "15.75",
        "CV": "0.08",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "15.79",
        "Date1": "13.57",
        "Date2": "14.71",
        "Date3": "15.13",
        "Date4": "15.62",
        "Date5": "16.09",
        "Date6": "17.00",
        "Date7": "14.21",
        "Date8": "17.36"
    },
    {
        "Item": "MPV",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-001",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "7.3",
        "AllowedMax": "9.9",
        "Unit": "fL",
        "SD": "0.72",
        "Mean": "8.60",
        "CV": "0.08",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "9.46",
        "Date1": "8.71",
        "Date2": "9.74",
        "Date3": "7.91",
        "Date4": "9.03",
        "Date5": "9.70",
        "Date6": "9.60",
        "Date7": "8.21",
        "Date8": "8.37"
    },
    {
        "Item": "Neutrophils no.",
        "Label": "Neutrophils #",
        "Structure -->": "",
        "Groups": "QC-001",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "2.2",
        "AllowedMax": "11.4",
        "Unit": "x 10^3/μL",
        "SD": "3.33",
        "Mean": "6.80",
        "CV": "0.49",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "9.60",
        "Date1": "2.27",
        "Date2": "8.21",
        "Date3": "2.26",
        "Date4": "3.55",
        "Date5": "2.36",
        "Date6": "11.14",
        "Date7": "2.78",
        "Date8": "5.86"
    },
    {
        "Item": "Lymphocytes no.",
        "Label": "Lymphocytes #",
        "Structure -->": "",
        "Groups": "QC-001",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "1.2",
        "AllowedMax": "5.7",
        "Unit": "x 10^3/μL",
        "SD": "1.57",
        "Mean": "3.45",
        "CV": "0.45",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "3.59",
        "Date1": "1.48",
        "Date2": "3.14",
        "Date3": "5.43",
        "Date4": "4.92",
        "Date5": "1.41",
        "Date6": "2.32",
        "Date7": "3.14",
        "Date8": "4.74"
    },
    {
        "Item": "Monocytes no.",
        "Label": "Monocytes #",
        "Structure -->": "",
        "Groups": "QC-001",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "0.1",
        "AllowedMax": "5.0",
        "Unit": "x 10^3/μL",
        "SD": "1.23",
        "Mean": "2.55",
        "CV": "0.48",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "0.29",
        "Date1": "1.18",
        "Date2": "1.22",
        "Date3": "0.63",
        "Date4": "2.83",
        "Date5": "2.13",
        "Date6": "1.61",
        "Date7": "3.17",
        "Date8": "4.30"
    },
    {
        "Item": "Eosinophils no.",
        "Label": "Eosinophils #",
        "Structure -->": "",
        "Groups": "QC-001",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "0.0",
        "AllowedMax": "0.5",
        "Unit": "x 10^3/μL",
        "SD": "0.18",
        "Mean": "0.25",
        "CV": "0.70",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "0.08",
        "Date1": "0.04",
        "Date2": "0.49",
        "Date3": "0.31",
        "Date4": "0.15",
        "Date5": "0.04",
        "Date6": "0.02",
        "Date7": "0.33",
        "Date8": "0.06"
    },
    {
        "Item": "Basophils no.",
        "Label": "Basophils #",
        "Structure -->": "",
        "Groups": "QC-001",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "0.0",
        "AllowedMax": "0.1",
        "Unit": "x 10^3/μL",
        "SD": "0.04",
        "Mean": "0.05",
        "CV": "0.71",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "0.09",
        "Date1": "0.09",
        "Date2": "0.06",
        "Date3": "0.01",
        "Date4": "0.00",
        "Date5": "0.03",
        "Date6": "0.06",
        "Date7": "0.02",
        "Date8": "0.10"
    },
    {
        "Item": "Neutrophils percent",
        "Label": "Neutrophils %",
        "Structure -->": "",
        "Groups": "QC-001",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "14.6",
        "AllowedMax": "69.3",
        "Unit": "%",
        "SD": "10.65",
        "Mean": "41.95",
        "CV": "0.25",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "67.14",
        "Date1": "49.53",
        "Date2": "59.76",
        "Date3": "43.49",
        "Date4": "54.12",
        "Date5": "25.95",
        "Date6": "48.41",
        "Date7": "35.86",
        "Date8": "49.10"
    },
    {
        "Item": "Lymphocytes percent",
        "Label": "Lymphocytes %",
        "Structure -->": "",
        "Groups": "QC-001",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "8.0",
        "AllowedMax": "70.0",
        "Unit": "%",
        "SD": "21.92",
        "Mean": "39.00",
        "CV": "0.56",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "68.06",
        "Date1": "62.95",
        "Date2": "23.43",
        "Date3": "69.22",
        "Date4": "19.11",
        "Date5": "24.22",
        "Date6": "11.97",
        "Date7": "31.93",
        "Date8": "14.14"
    },
    {
        "Item": "Monocytes percent",
        "Label": "Monocytes %",
        "Structure -->": "",
        "Groups": "QC-001",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "4.0",
        "AllowedMax": "19.0",
        "Unit": "%",
        "SD": "2.66",
        "Mean": "11.50",
        "CV": "0.23",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "11.84",
        "Date1": "13.76",
        "Date2": "8.17",
        "Date3": "10.09",
        "Date4": "14.21",
        "Date5": "15.48",
        "Date6": "12.84",
        "Date7": "9.04",
        "Date8": "10.52"
    },
    {
        "Item": "Eosinophils percent",
        "Label": "Eosinophils %",
        "Structure -->": "",
        "Groups": "QC-001",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "1.0",
        "AllowedMax": "7.0",
        "Unit": "%",
        "SD": "2.06",
        "Mean": "4.00",
        "CV": "0.51",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "4.37",
        "Date1": "3.43",
        "Date2": "4.11",
        "Date3": "2.65",
        "Date4": "1.18",
        "Date5": "2.26",
        "Date6": "6.00",
        "Date7": "6.80",
        "Date8": "6.15"
    },
    {
        "Item": "Basophils percent",
        "Label": "Basophils %",
        "Structure -->": "",
        "Groups": "QC-001",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "0.0",
        "AllowedMax": "1.0",
        "Unit": "%",
        "SD": "0.37",
        "Mean": "0.50",
        "CV": "0.75",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "0.42",
        "Date1": "0.10",
        "Date2": "0.84",
        "Date3": "0.61",
        "Date4": "0.84",
        "Date5": "0.99",
        "Date6": "0.87",
        "Date7": "0.89",
        "Date8": "0.03"
    },
    {
        "Item": "IG no.",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-001",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "0.0",
        "AllowedMax": "0.28",
        "Unit": "x 10^3/μL%",
        "SD": "0.07",
        "Mean": "0.14",
        "CV": "0.48",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "0.16",
        "Date1": "0.14",
        "Date2": "0.04",
        "Date3": "0.13",
        "Date4": "0.17",
        "Date5": "0.10",
        "Date6": "0.10",
        "Date7": "0.23",
        "Date8": "0.23"
    },
    {
        "Item": "IG percent",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-001",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "0.0",
        "AllowedMax": "1.7",
        "Unit": "%",
        "SD": "0.44",
        "Mean": "0.85",
        "CV": "0.52",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "0.61",
        "Date1": "0.25",
        "Date2": "1.45",
        "Date3": "0.85",
        "Date4": "0.24",
        "Date5": "0.33",
        "Date6": "0.86",
        "Date7": "0.48",
        "Date8": "0.17"
    },
    {
        "Item": "RET no.",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-001",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "29.0",
        "AllowedMax": "120.0",
        "Unit": "x 10^6/μL",
        "SD": "15.13",
        "Mean": "74.50",
        "CV": "0.20",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "73.32",
        "Date1": "74.85",
        "Date2": "64.07",
        "Date3": "65.74",
        "Date4": "61.19",
        "Date5": "87.36",
        "Date6": "100.05",
        "Date7": "92.74",
        "Date8": "63.84"
    },
    {
        "Item": "RET percent",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-001",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "0.4",
        "AllowedMax": "4.8",
        "Unit": "%",
        "SD": "1.38",
        "Mean": "2.60",
        "CV": "0.53",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "4.80",
        "Date1": "3.37",
        "Date2": "3.84",
        "Date3": "3.00",
        "Date4": "4.13",
        "Date5": "0.81",
        "Date6": "0.54",
        "Date7": "2.44",
        "Date8": "1.41"
    },
    {
        "Item": "QC-002",
        "Label": "",
        "Structure -->": "",
        "Groups": "QCSample",
        "Subgroup": "",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "",
        "AllowedMax": "",
        "Unit": "",
        "SD": "",
        "Mean": "",
        "CV": "",
        "Status": "OK",
        "Analysis dates -->": "8/1/2023 9:00:00; 9/9/2023 9:00:00; 9//15/2023 10:00:00",
        "Presenting": "10/3/2023 0:00:00",
        "Date1": "8/1/2023 9:00:00",
        "Date2": "9/9/2023 9:00:00",
        "Date3": "9//15/2023 10:00:00"
    },
    {
        "Item": "Material",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-002",
        "Subgroup": "SampleInfo",
        "Description Options -->": "",
        "Description": "XN-L Control Level 2"
    },
    {
        "Item": "Expiry Date",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-002",
        "Subgroup": "SampleInfo",
        "Description Options -->": "",
        "Description": "31/08/2023"
    },
    {
        "Item": "Cell Pack DCL",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-002",
        "Subgroup": "ReagentInfo"
    },
    {
        "Item": "Validated",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-002",
        "Subgroup": "RunInfo"
    },
    {
        "Item": "Output",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-002",
        "Subgroup": "RunInfo"
    },
    {
        "Item": "P / N",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-002",
        "Subgroup": "RunInfo"
    },
    {
        "Item": "Rack no.",
        "Label": "Rack #",
        "Structure -->": "",
        "Groups": "QC-002",
        "Subgroup": "RunInfo"
    },
    {
        "Item": "Position",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-002",
        "Subgroup": "RunInfo"
    },
    {
        "Item": "Action",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-002",
        "Subgroup": "RunInfo"
    },
    {
        "Item": "Error",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-002",
        "Subgroup": "RunInfo"
    },
    {
        "Item": "WBC",
        "Label": "WBC<sup>+4</sup>",
        "Structure -->": "",
        "Groups": "QC-002",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "5.9",
        "AllowedMax": "16.7",
        "Unit": "x 10^3/μL",
        "SD": "2.52",
        "Mean": "11.30",
        "CV": "0.22",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "7",
        "Date1": "8",
        "Date2": "10",
        "Date3": "13"
    },
    {
        "Item": "RBC",
        "Label": "RBC<sup>+4</sup>",
        "Structure -->": "",
        "Groups": "QC-002",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "3.2",
        "AllowedMax": "5.1",
        "Unit": "x 10^6/μL",
        "SD": "0.00",
        "Mean": "4.16",
        "CV": "0.00",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "4",
        "Date1": "4",
        "Date2": "4",
        "Date3": "4"
    },
    {
        "Item": "Hemoglobin",
        "Label": "HGB<sup>+4</sup>",
        "Structure -->": "",
        "Groups": "QC-002",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "10.2",
        "AllowedMax": "16.6",
        "Unit": "g/dL",
        "SD": "1.15",
        "Mean": "13.40",
        "CV": "0.09",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "11",
        "Date1": "11",
        "Date2": "11",
        "Date3": "13"
    },
    {
        "Item": "Hematocrit",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-002",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "29.1",
        "AllowedMax": "47.7",
        "Unit": "%",
        "SD": "2.89",
        "Mean": "38.40",
        "CV": "0.08",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "30",
        "Date1": "30",
        "Date2": "30",
        "Date3": "35"
    },
    {
        "Item": "MCV",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-002",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "75.6",
        "AllowedMax": "106.3",
        "Unit": "fL",
        "SD": "11.02",
        "Mean": "90.95",
        "CV": "0.12",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "100",
        "Date1": "80",
        "Date2": "100",
        "Date3": "82"
    },
    {
        "Item": "MCH",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-002",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "26.0",
        "AllowedMax": "36.4",
        "Unit": "pg",
        "SD": "2.89",
        "Mean": "31.20",
        "CV": "0.09",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "30",
        "Date1": "30",
        "Date2": "30",
        "Date3": "35"
    },
    {
        "Item": "MCHC",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-002",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "33.6",
        "AllowedMax": "35.7",
        "Unit": "g/dL",
        "SD": "0.00",
        "Mean": "34.65",
        "CV": "0.00",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "35",
        "Date1": "35",
        "Date2": "35",
        "Date3": "35"
    },
    {
        "Item": "Platelet",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-002",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "95.0",
        "AllowedMax": "471.0",
        "Unit": "x 10^3/μL",
        "SD": "104.50",
        "Mean": "283.00",
        "CV": "0.37",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "115",
        "Date1": "100",
        "Date2": "100",
        "Date3": "281"
    },
    {
        "Item": "RDW-SD",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-002",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "34.9",
        "AllowedMax": "65.7",
        "Unit": "fL",
        "SD": "2.89",
        "Mean": "50.30",
        "CV": "0.06",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "60",
        "Date1": "60",
        "Date2": "60",
        "Date3": "65"
    },
    {
        "Item": "RDW-CV",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-002",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "13.3",
        "AllowedMax": "18.2",
        "Unit": "%",
        "SD": "1.15",
        "Mean": "15.75",
        "CV": "0.07",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "15",
        "Date1": "15",
        "Date2": "15",
        "Date3": "17"
    },
    {
        "Item": "MPV",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-002",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "7.3",
        "AllowedMax": "9.9",
        "Unit": "fL",
        "SD": "0.00",
        "Mean": "8.60",
        "CV": "0.00",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "9",
        "Date1": "9",
        "Date2": "9",
        "Date3": "9"
    },
    {
        "Item": "Neutrophils no.",
        "Label": "Neutrophils #",
        "Structure -->": "",
        "Groups": "QC-002",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "2.2",
        "AllowedMax": "11.4",
        "Unit": "x 10^3/μL",
        "SD": "1.15",
        "Mean": "6.80",
        "CV": "0.17",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "3",
        "Date1": "5",
        "Date2": "3",
        "Date3": "5"
    },
    {
        "Item": "Lymphocytes no.",
        "Label": "Lymphocytes #",
        "Structure -->": "",
        "Groups": "QC-002",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "1.2",
        "AllowedMax": "5.7",
        "Unit": "x 10^3/μL",
        "SD": "1.15",
        "Mean": "3.45",
        "CV": "0.33",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "5",
        "Date1": "5",
        "Date2": "5",
        "Date3": "3"
    },
    {
        "Item": "Monocytes no.",
        "Label": "Monocytes #",
        "Structure -->": "",
        "Groups": "QC-002",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "0.1",
        "AllowedMax": "5.0",
        "Unit": "x 10^3/μL",
        "SD": "1.73",
        "Mean": "2.55",
        "CV": "0.68",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "5",
        "Date1": "5",
        "Date2": "5",
        "Date3": "2"
    },
    {
        "Item": "Eosinophils no.",
        "Label": "Eosinophils #",
        "Structure -->": "",
        "Groups": "QC-002",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "0.0",
        "AllowedMax": "0.5",
        "Unit": "x 10^3/μL",
        "SD": "0.29",
        "Mean": "0.25",
        "CV": "1.15",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "0.5",
        "Date1": "0.5",
        "Date2": "0.5",
        "Date3": "0"
    },
    {
        "Item": "Basophils no.",
        "Label": "Basophils #",
        "Structure -->": "",
        "Groups": "QC-002",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "0.0",
        "AllowedMax": "0.1",
        "Unit": "x 10^3/μL",
        "SD": "0.06",
        "Mean": "0.05",
        "CV": "1.15",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "0.1",
        "Date1": "0.1",
        "Date2": "0.1",
        "Date3": "0"
    },
    {
        "Item": "Neutrophils percent",
        "Label": "Neutrophils %",
        "Structure -->": "",
        "Groups": "QC-002",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "14.6",
        "AllowedMax": "69.3",
        "Unit": "%",
        "SD": "21.94",
        "Mean": "41.95",
        "CV": "0.52",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "69",
        "Date1": "69",
        "Date2": "69",
        "Date3": "31"
    },
    {
        "Item": "Lymphocytes percent",
        "Label": "Lymphocytes %",
        "Structure -->": "",
        "Groups": "QC-002",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "8.0",
        "AllowedMax": "70.0",
        "Unit": "%",
        "SD": "10.97",
        "Mean": "39.00",
        "CV": "0.28",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "70",
        "Date1": "70",
        "Date2": "70",
        "Date3": "51"
    },
    {
        "Item": "Monocytes percent",
        "Label": "Monocytes %",
        "Structure -->": "",
        "Groups": "QC-002",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "4.0",
        "AllowedMax": "19.0",
        "Unit": "%",
        "SD": "0.00",
        "Mean": "11.50",
        "CV": "0.00",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "19",
        "Date1": "19",
        "Date2": "19",
        "Date3": "19"
    },
    {
        "Item": "Eosinophils percent",
        "Label": "Eosinophils %",
        "Structure -->": "",
        "Groups": "QC-002",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "1.0",
        "AllowedMax": "7.0",
        "Unit": "%",
        "SD": "1.73",
        "Mean": "4.00",
        "CV": "0.43",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "7",
        "Date1": "7",
        "Date2": "7",
        "Date3": "4"
    },
    {
        "Item": "Basophils percent",
        "Label": "Basophils %",
        "Structure -->": "",
        "Groups": "QC-002",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "0.0",
        "AllowedMax": "1.0",
        "Unit": "%",
        "SD": "0.00",
        "Mean": "0.50",
        "CV": "0.00",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "1",
        "Date1": "1",
        "Date2": "1",
        "Date3": "1"
    },
    {
        "Item": "IG no.",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-002",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "0.0",
        "AllowedMax": "0.28",
        "Unit": "x 10^3/μL%",
        "SD": "0.12",
        "Mean": "0.14",
        "CV": "0.82",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "0.2",
        "Date1": "0.2",
        "Date2": "0.2",
        "Date3": "0"
    },
    {
        "Item": "IG percent",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-002",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "0.0",
        "AllowedMax": "1.7",
        "Unit": "%",
        "SD": "0.00",
        "Mean": "0.85",
        "CV": "0.00",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "1",
        "Date1": "1",
        "Date2": "1",
        "Date3": "1"
    },
    {
        "Item": "RET no.",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-002",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "29.0",
        "AllowedMax": "120.0",
        "Unit": "x 10^6/μL",
        "SD": "40.41",
        "Mean": "74.50",
        "CV": "0.54",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "100",
        "Date1": "100",
        "Date2": "100",
        "Date3": "30"
    },
    {
        "Item": "RET percent",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-002",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "0.4",
        "AllowedMax": "4.8",
        "Unit": "%",
        "SD": "",
        "Mean": "",
        "CV": "",
        "Status": "2.6",
        "Analysis dates -->": "",
        "Presenting": "1",
        "Date1": "1",
        "Date2": "1",
        "Date3": "3"
    },
    {
        "Item": "P12345",
        "Label": "",
        "Structure -->": "",
        "Groups": "PASample",
        "Subgroup": "",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "",
        "AllowedMax": "",
        "Unit": "",
        "SD": "",
        "Mean": "",
        "CV": "",
        "Status": "Err-range",
        "Analysis dates -->": "8/1/2023 11:27:55; 9/1/2023 1:27:56; ; ; ; ; ; ",
        "Presenting": "10/3/2023 0:00:00",
        "Date1": "8/1/2023 11:27:55",
        "Date2": "9/1/2023 1:27:56"
    },
    {
        "Item": "Patient id",
        "Label": "",
        "Structure -->": "",
        "Groups": "P12345",
        "Subgroup": "PatientInfo",
        "Description Options -->": "",
        "Description": "MRN"
    },
    {
        "Item": "name",
        "Label": "",
        "Structure -->": "",
        "Groups": "P12345",
        "Subgroup": "PatientInfo",
        "Description Options -->": "",
        "Description": "Jon Doe"
    },
    {
        "Item": "sex",
        "Label": "",
        "Structure -->": "",
        "Groups": "P12345",
        "Subgroup": "PatientInfo",
        "Description Options -->": "",
        "Description": "M"
    },
    {
        "Item": "age",
        "Label": "",
        "Structure -->": "",
        "Groups": "P12345",
        "Subgroup": "PatientInfo",
        "Description Options -->": "",
        "Description": "50"
    },
    {
        "Item": "ward",
        "Label": "",
        "Structure -->": "",
        "Groups": "P12345",
        "Subgroup": "PatientInfo",
        "Description Options -->": "",
        "Description": "7"
    },
    {
        "Item": "doctor",
        "Label": "",
        "Structure -->": "",
        "Groups": "P12345",
        "Subgroup": "PatientInfo",
        "Description Options -->": "",
        "Description": "M.D"
    },
    {
        "Item": "Cell Pack DCL",
        "Label": "",
        "Structure -->": "",
        "Groups": "P12345",
        "Subgroup": "ReagentInfo",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "",
        "AllowedMax": "",
        "Unit": "",
        "SD": "",
        "Mean": "",
        "CV": "",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "Y3006",
        "Date1": "Y3007",
        "Date2": "Y3008",
        "Date3": "Y3009"
    },
    {
        "Item": "Sulfoyser",
        "Label": "",
        "Structure -->": "",
        "Groups": "P12345",
        "Subgroup": "ReagentInfo",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "",
        "AllowedMax": "",
        "Unit": "",
        "SD": "",
        "Mean": "",
        "CV": "",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "A2014",
        "Date1": "A2015",
        "Date2": "A2016",
        "Date3": "A2017"
    },
    {
        "Item": "Lysercell WDF",
        "Label": "",
        "Structure -->": "",
        "Groups": "P12345",
        "Subgroup": "ReagentInfo",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "",
        "AllowedMax": "",
        "Unit": "",
        "SD": "",
        "Mean": "",
        "CV": "",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "Y2061",
        "Date1": "Y2062",
        "Date2": "Y2063",
        "Date3": "Y2064"
    },
    {
        "Item": "Validated",
        "Label": "",
        "Structure -->": "",
        "Groups": "P12345",
        "Subgroup": "RunInfo",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "",
        "AllowedMax": "",
        "Unit": "",
        "SD": "",
        "Mean": "",
        "CV": "",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "",
        "Date1": "V",
        "Date2": "V"
    },
    {
        "Item": "Output",
        "Label": "",
        "Structure -->": "",
        "Groups": "P12345",
        "Subgroup": "RunInfo",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "",
        "AllowedMax": "",
        "Unit": "",
        "SD": "",
        "Mean": "",
        "CV": "",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "",
        "Date1": "GH",
        "Date2": "G"
    },
    {
        "Item": "P / N",
        "Label": "",
        "Structure -->": "",
        "Groups": "P12345",
        "Subgroup": "RunInfo",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "",
        "AllowedMax": "",
        "Unit": "",
        "SD": "",
        "Mean": "",
        "CV": "",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "",
        "Date1": "M"
    },
    {
        "Item": "Rack no.",
        "Label": "Rack #",
        "Structure -->": "",
        "Groups": "P12345",
        "Subgroup": "RunInfo",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "",
        "AllowedMax": "",
        "Unit": "",
        "SD": "",
        "Mean": "",
        "CV": "",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "",
        "Date1": "2"
    },
    {
        "Item": "Position",
        "Label": "",
        "Structure -->": "",
        "Groups": "P12345",
        "Subgroup": "RunInfo",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "",
        "AllowedMax": "",
        "Unit": "",
        "SD": "",
        "Mean": "",
        "CV": "",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "",
        "Date1": "1"
    },
    {
        "Item": "Action",
        "Label": "",
        "Structure -->": "",
        "Groups": "P12345",
        "Subgroup": "RunInfo",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "",
        "AllowedMax": "",
        "Unit": "",
        "SD": "",
        "Mean": "",
        "CV": "",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "",
        "Date1": "-",
        "Date2": "-"
    },
    {
        "Item": "Error",
        "Label": "",
        "Structure -->": "",
        "Groups": "P12345",
        "Subgroup": "RunInfo",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "",
        "AllowedMax": "",
        "Unit": "",
        "SD": "",
        "Mean": "",
        "CV": "",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "",
        "Date1": "-",
        "Date2": "-"
    },
    {
        "Item": "Scatterplot",
        "Label": "",
        "Structure -->": "",
        "Groups": "P12345",
        "Subgroup": "RunInfo",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "",
        "AllowedMax": "",
        "Unit": "",
        "SD": "",
        "Mean": "",
        "CV": "",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "file name source path",
        "Date1": "file name source path",
        "Date2": "file name source path"
    },
    {
        "Item": "WBC",
        "Label": "WBC<sup>+4</sup>",
        "Structure -->": "",
        "Groups": "P12345",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "5.9",
        "AllowedMax": "16.7",
        "Unit": "x 10^3/μL",
        "SD": "",
        "Mean": "",
        "CV": "",
        "Status": "11.3",
        "Analysis dates -->": "",
        "Presenting": "6",
        "Date1": "7"
    },
    {
        "Item": "RBC",
        "Label": "RBC<sup>+4</sup>",
        "Structure -->": "",
        "Groups": "P12345",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "3.2",
        "AllowedMax": "5.1",
        "Unit": "x 10^6/μL",
        "SD": "",
        "Mean": "",
        "CV": "",
        "Status": "4.2",
        "Analysis dates -->": "",
        "Presenting": "4",
        "Date1": "5"
    },
    {
        "Item": "Hemoglobin",
        "Label": "HGB<sup>+4</sup>",
        "Structure -->": "",
        "Groups": "P12345",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "10.2",
        "AllowedMax": "16.6",
        "Unit": "g/dL",
        "SD": "",
        "Mean": "",
        "CV": "",
        "Status": "13.4",
        "Analysis dates -->": "",
        "Presenting": "11",
        "Date1": "12"
    },
    {
        "Item": "Hematocrit",
        "Label": "",
        "Structure -->": "",
        "Groups": "P12345",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "29.1",
        "AllowedMax": "47.7",
        "Unit": "%",
        "SD": "",
        "Mean": "",
        "CV": "",
        "Status": "38.4",
        "Analysis dates -->": "",
        "Presenting": "30",
        "Date1": "31"
    },
    {
        "Item": "MCV",
        "Label": "",
        "Structure -->": "",
        "Groups": "P12345",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "75.6",
        "AllowedMax": "106.3",
        "Unit": "fL",
        "SD": "",
        "Mean": "",
        "CV": "",
        "Status": "91.0",
        "Analysis dates -->": "",
        "Presenting": "100",
        "Date1": "101"
    },
    {
        "Item": "MCH",
        "Label": "",
        "Structure -->": "",
        "Groups": "P12345",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "26.0",
        "AllowedMax": "36.4",
        "Unit": "pg",
        "SD": "",
        "Mean": "",
        "CV": "",
        "Status": "31.2",
        "Analysis dates -->": "",
        "Presenting": "30",
        "Date1": "31"
    },
    {
        "Item": "MCHC",
        "Label": "",
        "Structure -->": "",
        "Groups": "P12345",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "33.6",
        "AllowedMax": "35.7",
        "Unit": "g/dL",
        "SD": "",
        "Mean": "",
        "CV": "",
        "Status": "34.7",
        "Analysis dates -->": "",
        "Presenting": "35",
        "Date1": "36"
    },
    {
        "Item": "Platelet",
        "Label": "",
        "Structure -->": "",
        "Groups": "P12345",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "95.0",
        "AllowedMax": "471.0",
        "Unit": "x 10^3/μL",
        "SD": "",
        "Mean": "",
        "CV": "",
        "Status": "283.0",
        "Analysis dates -->": "",
        "Presenting": "100",
        "Date1": "101"
    },
    {
        "Item": "RDW-SD",
        "Label": "",
        "Structure -->": "",
        "Groups": "P12345",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "34.9",
        "AllowedMax": "65.7",
        "Unit": "fL",
        "SD": "",
        "Mean": "",
        "CV": "",
        "Status": "50.3",
        "Analysis dates -->": "",
        "Presenting": "60",
        "Date1": "61"
    },
    {
        "Item": "RDW-CV",
        "Label": "",
        "Structure -->": "",
        "Groups": "P12345",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "13.3",
        "AllowedMax": "18.2",
        "Unit": "%",
        "SD": "",
        "Mean": "",
        "CV": "",
        "Status": "15.8",
        "Analysis dates -->": "",
        "Presenting": "15",
        "Date1": "16"
    },
    {
        "Item": "MPV",
        "Label": "",
        "Structure -->": "",
        "Groups": "P12345",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "7.3",
        "AllowedMax": "9.9",
        "Unit": "fL",
        "SD": "",
        "Mean": "",
        "CV": "",
        "Status": "8.6",
        "Analysis dates -->": "",
        "Presenting": "9",
        "Date1": "10"
    },
    {
        "Item": "Neutrophils no.",
        "Label": "Neutrophils #",
        "Structure -->": "",
        "Groups": "P12345",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "2.2",
        "AllowedMax": "11.4",
        "Unit": "x 10^3/μL",
        "SD": "",
        "Mean": "",
        "CV": "",
        "Status": "6.8",
        "Analysis dates -->": "",
        "Presenting": "3",
        "Date1": "4"
    },
    {
        "Item": "Lymphocytes no.",
        "Label": "Lymphocytes #",
        "Structure -->": "",
        "Groups": "P12345",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "1.2",
        "AllowedMax": "5.7",
        "Unit": "x 10^3/μL",
        "SD": "",
        "Mean": "",
        "CV": "",
        "Status": "3.5",
        "Analysis dates -->": "",
        "Presenting": "5",
        "Date1": "6"
    },
    {
        "Item": "Monocytes no.",
        "Label": "Monocytes #",
        "Structure -->": "",
        "Groups": "P12345",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "0.1",
        "AllowedMax": "5.0",
        "Unit": "x 10^3/μL",
        "SD": "",
        "Mean": "",
        "CV": "",
        "Status": "2.6",
        "Analysis dates -->": "",
        "Presenting": "5",
        "Date1": "6"
    },
    {
        "Item": "Eosinophils no.",
        "Label": "Eosinophils #",
        "Structure -->": "",
        "Groups": "P12345",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "0.0",
        "AllowedMax": "0.5",
        "Unit": "x 10^3/μL",
        "SD": "",
        "Mean": "",
        "CV": "",
        "Status": "0.3",
        "Analysis dates -->": "",
        "Presenting": "0.5",
        "Date1": "1.5"
    },
    {
        "Item": "Basophils no.",
        "Label": "Basophils #",
        "Structure -->": "",
        "Groups": "P12345",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "0.0",
        "AllowedMax": "0.1",
        "Unit": "x 10^3/μL",
        "SD": "",
        "Mean": "",
        "CV": "",
        "Status": "0.1",
        "Analysis dates -->": "",
        "Presenting": "0.1",
        "Date1": "1.1"
    },
    {
        "Item": "Neutrophils percent",
        "Label": "Neutrophils %",
        "Structure -->": "",
        "Groups": "P12345",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "14.6",
        "AllowedMax": "69.3",
        "Unit": "%",
        "SD": "",
        "Mean": "",
        "CV": "",
        "Status": "42.0",
        "Analysis dates -->": "",
        "Presenting": "69",
        "Date1": "70"
    },
    {
        "Item": "Lymphocytes percent",
        "Label": "Lymphocytes %",
        "Structure -->": "",
        "Groups": "P12345",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "8.0",
        "AllowedMax": "70.0",
        "Unit": "%",
        "SD": "",
        "Mean": "",
        "CV": "",
        "Status": "39.0",
        "Analysis dates -->": "",
        "Presenting": "70",
        "Date1": "71"
    },
    {
        "Item": "Monocytes percent",
        "Label": "Monocytes %",
        "Structure -->": "",
        "Groups": "P12345",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "4.0",
        "AllowedMax": "19.0",
        "Unit": "%",
        "SD": "",
        "Mean": "",
        "CV": "",
        "Status": "11.5",
        "Analysis dates -->": "",
        "Presenting": "19",
        "Date1": "20"
    },
    {
        "Item": "Eosinophils percent",
        "Label": "Eosinophils %",
        "Structure -->": "",
        "Groups": "P12345",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "1.0",
        "AllowedMax": "7.0",
        "Unit": "%",
        "SD": "",
        "Mean": "",
        "CV": "",
        "Status": "4.0",
        "Analysis dates -->": "",
        "Presenting": "7",
        "Date1": "8"
    },
    {
        "Item": "Basophils percent",
        "Label": "Basophils %",
        "Structure -->": "",
        "Groups": "P12345",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "0.0",
        "AllowedMax": "1.0",
        "Unit": "%",
        "SD": "",
        "Mean": "",
        "CV": "",
        "Status": "0.5",
        "Analysis dates -->": "",
        "Presenting": "1",
        "Date1": "2"
    },
    {
        "Item": "IG no.",
        "Label": "",
        "Structure -->": "",
        "Groups": "P12345",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "0.0",
        "AllowedMax": "0.28",
        "Unit": "x 10^3/μL%",
        "SD": "",
        "Mean": "",
        "CV": "",
        "Status": "0.1",
        "Analysis dates -->": "",
        "Presenting": "0.2",
        "Date1": "1.2"
    },
    {
        "Item": "IG percent",
        "Label": "",
        "Structure -->": "",
        "Groups": "P12345",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "0.0",
        "AllowedMax": "1.7",
        "Unit": "%",
        "SD": "",
        "Mean": "",
        "CV": "",
        "Status": "0.9",
        "Analysis dates -->": "",
        "Presenting": "1",
        "Date1": "2"
    },
    {
        "Item": "RET no.",
        "Label": "",
        "Structure -->": "",
        "Groups": "P12345",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "29.0",
        "AllowedMax": "120.0",
        "Unit": "x 10^6/μL",
        "SD": "",
        "Mean": "",
        "CV": "",
        "Status": "74.5",
        "Analysis dates -->": "",
        "Presenting": "100",
        "Date1": "101"
    },
    {
        "Item": "RET percent",
        "Label": "",
        "Structure -->": "",
        "Groups": "P12345",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "0.4",
        "AllowedMax": "4.8",
        "Unit": "%",
        "SD": "",
        "Mean": "",
        "CV": "",
        "Status": "2.6",
        "Analysis dates -->": "",
        "Presenting": "1",
        "Date1": "2"
    },
    {
        "Item": "QC-003",
        "Label": "",
        "Structure -->": "",
        "Groups": "QCSample",
        "Subgroup": "",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "",
        "AllowedMax": "",
        "Unit": "",
        "SD": "",
        "Mean": "",
        "CV": "",
        "Status": "Err-range",
        "Analysis dates -->": "8/1/2023 9:00:00; 9/9/2023 9:00:00; 9//15/2023 10:00:00",
        "Presenting": "10/3/2023 0:00:00",
        "Date1": "8/1/2023 9:00:00",
        "Date2": "9/9/2023 9:00:00",
        "Date3": "9//15/2023 10:00:00"
    },
    {
        "Item": "Material",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-003",
        "Subgroup": "SampleInfo",
        "Description Options -->": "",
        "Description": "XN-L Control Level 3"
    },
    {
        "Item": "Expiry Date",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-003",
        "Subgroup": "SampleInfo",
        "Description Options -->": "",
        "Description": "31/08/2023"
    },
    {
        "Item": "Cell Pack DCL",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-003",
        "Subgroup": "ReagentInfo",
        "Description Options -->": "",
        "Description": "qc-003 reagent"
    },
    {
        "Item": "Validated",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-003",
        "Subgroup": "RunInfo"
    },
    {
        "Item": "Output",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-003",
        "Subgroup": "RunInfo"
    },
    {
        "Item": "P / N",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-003",
        "Subgroup": "RunInfo"
    },
    {
        "Item": "Rack no.",
        "Label": "Rack #",
        "Structure -->": "",
        "Groups": "QC-003",
        "Subgroup": "RunInfo"
    },
    {
        "Item": "Position",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-003",
        "Subgroup": "RunInfo"
    },
    {
        "Item": "Action",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-003",
        "Subgroup": "RunInfo"
    },
    {
        "Item": "Error",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-003",
        "Subgroup": "RunInfo"
    },
    {
        "Item": "WBC",
        "Label": "WBC<sup>+4</sup>",
        "Structure -->": "",
        "Groups": "QC-003",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "5.9",
        "AllowedMax": "16.7",
        "Unit": "x 10^3/μL",
        "SD": "4.58",
        "Mean": "11.30",
        "CV": "0.41",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "7",
        "Date1": "4",
        "Date2": "10",
        "Date3": "13"
    },
    {
        "Item": "RBC",
        "Label": "RBC<sup>+4</sup>",
        "Structure -->": "",
        "Groups": "QC-003",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "3.2",
        "AllowedMax": "5.1",
        "Unit": "x 10^6/μL",
        "SD": "0.00",
        "Mean": "4.16",
        "CV": "0.00",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "4",
        "Date1": "4",
        "Date2": "4",
        "Date3": "4"
    },
    {
        "Item": "Hemoglobin",
        "Label": "HGB<sup>+4</sup>",
        "Structure -->": "",
        "Groups": "QC-003",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "10.2",
        "AllowedMax": "16.6",
        "Unit": "g/dL",
        "SD": "0.00",
        "Mean": "13.40",
        "CV": "0.00",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "11",
        "Date1": "11",
        "Date2": "11",
        "Date3": "11"
    },
    {
        "Item": "Hematocrit",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-003",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "29.1",
        "AllowedMax": "47.7",
        "Unit": "%",
        "SD": "0.00",
        "Mean": "38.40",
        "CV": "0.00",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "30",
        "Date1": "30",
        "Date2": "30",
        "Date3": "30"
    },
    {
        "Item": "MCV",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-003",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "75.6",
        "AllowedMax": "106.3",
        "Unit": "fL",
        "SD": "4.04",
        "Mean": "90.95",
        "CV": "0.04",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "100",
        "Date1": "100",
        "Date2": "100",
        "Date3": "93"
    },
    {
        "Item": "MCH",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-003",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "26.0",
        "AllowedMax": "36.4",
        "Unit": "pg",
        "SD": "1.73",
        "Mean": "31.20",
        "CV": "0.06",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "30",
        "Date1": "30",
        "Date2": "30",
        "Date3": "27"
    },
    {
        "Item": "MCHC",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-003",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "33.6",
        "AllowedMax": "35.7",
        "Unit": "g/dL",
        "SD": "1.73",
        "Mean": "34.65",
        "CV": "0.05",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "35",
        "Date1": "35",
        "Date2": "35",
        "Date3": "32"
    },
    {
        "Item": "Platelet",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-003",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "95.0",
        "AllowedMax": "471.0",
        "Unit": "x 10^3/μL",
        "SD": "154.15",
        "Mean": "283.00",
        "CV": "0.54",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "115",
        "Date1": "100",
        "Date2": "100",
        "Date3": "367"
    },
    {
        "Item": "RDW-SD",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-003",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "34.9",
        "AllowedMax": "65.7",
        "Unit": "fL",
        "SD": "10.39",
        "Mean": "50.30",
        "CV": "0.21",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "60",
        "Date1": "60",
        "Date2": "60",
        "Date3": "42"
    },
    {
        "Item": "RDW-CV",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-003",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "13.3",
        "AllowedMax": "18.2",
        "Unit": "%",
        "SD": "0.00",
        "Mean": "15.75",
        "CV": "0.00",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "15",
        "Date1": "15",
        "Date2": "15",
        "Date3": "15"
    },
    {
        "Item": "MPV",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-003",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "7.3",
        "AllowedMax": "9.9",
        "Unit": "fL",
        "SD": "0.58",
        "Mean": "8.60",
        "CV": "0.07",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "9",
        "Date1": "9",
        "Date2": "9",
        "Date3": "8"
    },
    {
        "Item": "Neutrophils no.",
        "Label": "Neutrophils #",
        "Structure -->": "",
        "Groups": "QC-003",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "2.2",
        "AllowedMax": "11.4",
        "Unit": "x 10^3/μL",
        "SD": "1.15",
        "Mean": "6.80",
        "CV": "0.17",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "3",
        "Date1": "5",
        "Date2": "3",
        "Date3": "3"
    },
    {
        "Item": "Lymphocytes no.",
        "Label": "Lymphocytes #",
        "Structure -->": "",
        "Groups": "QC-003",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "1.2",
        "AllowedMax": "5.7",
        "Unit": "x 10^3/μL",
        "SD": "0.00",
        "Mean": "3.45",
        "CV": "0.00",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "5",
        "Date1": "5",
        "Date2": "5",
        "Date3": "5"
    },
    {
        "Item": "Monocytes no.",
        "Label": "Monocytes #",
        "Structure -->": "",
        "Groups": "QC-003",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "0.1",
        "AllowedMax": "5.0",
        "Unit": "x 10^3/μL",
        "SD": "1.15",
        "Mean": "2.55",
        "CV": "0.45",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "5",
        "Date1": "5",
        "Date2": "5",
        "Date3": "3"
    },
    {
        "Item": "Eosinophils no.",
        "Label": "Eosinophils #",
        "Structure -->": "",
        "Groups": "QC-003",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "0.0",
        "AllowedMax": "0.5",
        "Unit": "x 10^3/μL",
        "SD": "0.29",
        "Mean": "0.25",
        "CV": "1.15",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "0.5",
        "Date1": "0.5",
        "Date2": "0.5",
        "Date3": "0"
    },
    {
        "Item": "Basophils no.",
        "Label": "Basophils #",
        "Structure -->": "",
        "Groups": "QC-003",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "0.0",
        "AllowedMax": "0.1",
        "Unit": "x 10^3/μL",
        "SD": "0.06",
        "Mean": "0.05",
        "CV": "1.15",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "0.1",
        "Date1": "0.1",
        "Date2": "0.1",
        "Date3": "0"
    },
    {
        "Item": "Neutrophils percent",
        "Label": "Neutrophils %",
        "Structure -->": "",
        "Groups": "QC-003",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "14.6",
        "AllowedMax": "69.3",
        "Unit": "%",
        "SD": "25.98",
        "Mean": "41.95",
        "CV": "0.62",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "69",
        "Date1": "69",
        "Date2": "69",
        "Date3": "24"
    },
    {
        "Item": "Lymphocytes percent",
        "Label": "Lymphocytes %",
        "Structure -->": "",
        "Groups": "QC-003",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "8.0",
        "AllowedMax": "70.0",
        "Unit": "%",
        "SD": "23.09",
        "Mean": "39.00",
        "CV": "0.59",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "70",
        "Date1": "70",
        "Date2": "70",
        "Date3": "30"
    },
    {
        "Item": "Monocytes percent",
        "Label": "Monocytes %",
        "Structure -->": "",
        "Groups": "QC-003",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "4.0",
        "AllowedMax": "19.0",
        "Unit": "%",
        "SD": "5.20",
        "Mean": "11.50",
        "CV": "0.45",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "19",
        "Date1": "19",
        "Date2": "19",
        "Date3": "10"
    },
    {
        "Item": "Eosinophils percent",
        "Label": "Eosinophils %",
        "Structure -->": "",
        "Groups": "QC-003",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "1.0",
        "AllowedMax": "7.0",
        "Unit": "%",
        "SD": "1.15",
        "Mean": "4.00",
        "CV": "0.29",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "7",
        "Date1": "7",
        "Date2": "7",
        "Date3": "5"
    },
    {
        "Item": "Basophils percent",
        "Label": "Basophils %",
        "Structure -->": "",
        "Groups": "QC-003",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "0.0",
        "AllowedMax": "1.0",
        "Unit": "%",
        "SD": "0.58",
        "Mean": "0.50",
        "CV": "1.15",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "1",
        "Date1": "1",
        "Date2": "1",
        "Date3": "0"
    },
    {
        "Item": "IG no.",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-003",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "0.0",
        "AllowedMax": "0.28",
        "Unit": "x 10^3/μL%",
        "SD": "0.12",
        "Mean": "0.14",
        "CV": "0.82",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "0.2",
        "Date1": "0.2",
        "Date2": "0.2",
        "Date3": "0"
    },
    {
        "Item": "IG percent",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-003",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "0.0",
        "AllowedMax": "1.7",
        "Unit": "%",
        "SD": "0.00",
        "Mean": "0.85",
        "CV": "0.00",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "1",
        "Date1": "1",
        "Date2": "1",
        "Date3": "1"
    },
    {
        "Item": "RET no.",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-003",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "29.0",
        "AllowedMax": "120.0",
        "Unit": "x 10^6/μL",
        "SD": "5.20",
        "Mean": "74.50",
        "CV": "0.07",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "100",
        "Date1": "100",
        "Date2": "100",
        "Date3": "91"
    },
    {
        "Item": "RET percent",
        "Label": "",
        "Structure -->": "",
        "Groups": "QC-003",
        "Subgroup": "HAParameter",
        "Description Options -->": "",
        "Description": "",
        "AllowedMin": "0.4",
        "AllowedMax": "4.8",
        "Unit": "%",
        "SD": "0.58",
        "Mean": "2.60",
        "CV": "0.22",
        "Status": "",
        "Analysis dates -->": "",
        "Presenting": "1",
        "Date1": "1",
        "Date2": "1",
        "Date3": "2"
    }
] as Record<string, string>[];